server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tabela-fipe
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fipe}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fipe}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  security:
    username: ${APP_SECURITY_USERNAME:admin}
    password: ${APP_SECURITY_PASSWORD:admin123}
  messaging:
    initial-load-queue: ${APP_INITIAL_LOAD_QUEUE:fipe.initial-load.queue}
  cache:
    brands-key-prefix: ${APP_CACHE_BRANDS_KEY_PREFIX:fipe:brands}
    vehicles-key-prefix: ${APP_CACHE_VEHICLES_KEY_PREFIX:fipe:vehicles:}
  fipe-api:
    base-url: ${FIPE_API_BASE_URL:https://fipe.parallelum.com.br/api/v2}
    default-vehicle-type: ${FIPE_DEFAULT_VEHICLE_TYPE:cars}
    default-reference: ${FIPE_DEFAULT_REFERENCE:278}
    subscription-token: ${FIPE_SUBSCRIPTION_TOKEN:}
